services:
  app:
    build: .
    volumes:
      - .:/home/node/app
    ports:
      - 3002:3002
  db:
    build: ./.docker/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017