###
GET http://localhost:3000/hello
###
GET http://localhost:3000/places?text=Rua Campinas, 180, Catanduva
###
GET http://localhost:3000/places?text=Rua Martinho CAnozo, 250, Catanduva
### 
@originId = ChIJseDhm4YevJQRZAY9m1osCSQ
@destinationId = ChIJ74QbW78fvJQRfBAK2fEucXs
###
GET http://localhost:3000/directions?originId={{ originId }}&destinationId={{ destinationId }}

###
POST http://localhost:3000/routes

Content-Type: application/json
{
    "name": "Minha Rota 1",
    "source_id": "{{ originId }}",
    "destination_id": "{{ destinationId }}"
}

###
GET http://localhost:3000/routes

###
GET http://localhost:3000/routes/674ef78bab1148ea9161c23b